// <auto-generated />
namespace Erbsenzaehler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RefundDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefundDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201405181229284_RefundDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
